server:
  port: 8088
spring:
  application:
    name: test-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      #路由
      routes:
        #id可随意 ,不能少,不能重复
        - id: client-test
          #转发的微服务的名称
          #uri: lb://SERVICE-FEIGN client-test
          uri: lb://CLIENT-TEST
          #断言
          predicates:
            - Path=/testclient/**
          filters:
            - StripPrefix=1  #访问路径是否包含testclient,不可缺少
            - name: Hystrix  #Retry为重试 ,retries:设置重试的次数,Hystrix为熔断回退
            #- name: RequestRateLimiter
              args:
                #redis-rate-limiter.replenishRate: 1
                #redis-rate-limiter.burstCapacity: 1
                #key-resolver: "#{@userKeyResolver}"
                name: defaultfallback
                fallbackUri: forward:/defaultfallback

  #跨域
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          exposedHeaders:
             - content-type
          allowedHeaders:
             - content-type
          allowCredentials: true
          allowedMethods:
             - GET
             - OPTIONS
             - PUT
             - DELETE
             - POST
#redis
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 全局熔断器5s超时
            timeoutInMilliseconds: 5000


